[package]
name = "diesel_demo_step_2_pg"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "1.4.0", features = ["postgres"] }
dotenv = "0.10"

[[bin]]
name = "show_posts"
doc = false

[[bin]]
name = "write_post"
doc = false

[lib]
doc = false
